---
- name: "Add repository"
  hosts: "{{ host }}"
  become: yes
  vars_files:
    - secret
  ansible.builtin.yum_repository:
    name: postgree_repo
    description: postgree_repo
    baseurl: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm