---
- name: "Test playbook run"
  hosts: all
  tasks:
    - name: "Debug"
      ansible.builtin.debug:
        msg: "Test debug"
    - name: install wget
      yum:
        name: wget
        state: latest
