---
- name: "Test playbook run"
  hosts: all
  tasks:
    - name: "Debug"
      ansible.builtin.debug:
        msg: "Test debug"
    - name: full system upgrade
      become: yes
      pacman:
        update_cache: yes
        upgrade: yes
