---
- name: "Restart network"
  hosts: "{{ host }}"
  become: true
  remote_user: kafka
  tasks:
    - name: Run command systemctl
      command:
        cmd: sudo systemctl restart "{{ demon_name }}"
      register: output
    - name: Check demon status
        commands: sudo systemctl status "{{ demon_name }}"
      register: result
    - name: Debug registered var
      debug: var=result.stdout_lines
