---
- name: "Restart network"
  hosts: "{{ host }}"
  become: true
  remote_user: kafka
  tasks:
    - name: Run command systemctl
      command:
        cmd: sudo systemctl restart "{{ demon_name }}"
    - name: Check demon status
      command:
        cmd: sudo systemctl status "{{ demon_name }}"
