---
- name: "Test playbook run"
  hosts: all
  become: true
  remote_user: kafka
  tasks:
    - name: unzip zookeeper
      ansible.builtin.unarchive:
        src: /home/kafka/apache-zookeeper-3.8.1-bin.tar.gz
        dest: /opt/zookeeper
