---
- name: "Run commanm playbook"
  hosts: "{{ host }}"
  become: true
  vars_files:
    - secret
  tasks:
    - name: run command - "{{ command }}"
      shell: "{{ command }}"
      register: result
    - name: Debug registered var
      debug:
        msg: result.stdout_lines