---
- name: "Run commanm playbook"
  hosts: "{{ host }}"
  become: true
  vars_files:
    - secret
  tasks:
    - name: run command - "{{ command }}"
      command:
        cmd: "{{ command }}"
      register: result
    - name: Debug registered var
      debug: var=result.stdout_lines