---
- name: "Install node exporter"
  hosts: "{{ host }}"
  become: true
  vars_files:
    - secret
  tasks:
    - name: Download node exporter
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz
        dest: "/tmp"
        validate_certs: false
    - name: Create user node_exporter
      user:
        name: node_exporter
        create_home: false
    - name: Make dir /opt/node_exporter
      file:
        path: /opt/node_exporter
        state: directory
        mode: '0755'
    - name: Unzip node_exporter
      unarchive:
        src: /tmp/node_exporter-1.5.0.linux-amd64.tar.gz
        dest: /opt/node_exporter
        validate_certs: false
    - name: Copy run file
      copy:
        src: /opt/node_exporter/node_exporter
        dest: /usr/local/bin
    - name: Make kafka_exporter demon
      copy:
        src: ./install_node_exporter/node_exporter.service
        dest: /etc/systemd/system/
        owner: node_exporter
        group: node_exporter
        mode: u=rw,g=r,o=r
    - name: Open node_exporter port
      firewalld:
        port: 9101/tcp
        permanent: true
        state: enabled
    - name: Reload firewalld
      command: firewall-cmd --reload
    - name: Enable node_exporter
      service:
        name: node_exporter
        state: started
        enabled: yes