---
- name: "Get list topic"
  hosts: "{{ host }}"
  become: true
  vars_files:
    - secret
  tasks:
    - name: Run command
      command:
        cmd: sudo /opt/kafka/bin/kafka-topics.sh --bootstrap-server "{{ SERVER }}":"{{ PORT }}" --list
      register: result
    - name: Print topic list
      debug: var=result.stdout_lines
